### ISSUE TITLE
Don't recompile assembly if it already is compiled (same as #17)

### ISSUE THREAD

**Issue by nightroman** [intellifactory/websharper.warp#20]
Don't recompile assembly if it already is compiled (same as #17)

Perhaps I misunderstand the resolved #17 but an assembly is always compiled,
i.e. js scripts are generated on each run.

After looking at the code, I started to think that I should tell to call
`getCompiled` instead of `compile`, that is use the option `scripted=false` for
`Warp.RunAndWaitForInput`. But this scenario always fails with

    "Assembly not compiled. When using Scripted = false, the application must be precompiled."

It is not clear how it is supposed to be precompiled. It is already
"precompiled", in a way, I do not change the assembly, all scripts are
generated at the last run. But they are not "discovered and reused".

I started to think that something has changed since #17. Is this the case?

Anyway, I tried to solve the issue by adding the following code to `getCompiled`.
When it is about to fail with the above message, I check time stamps of the
assembly and existing scripts. If scripts are up to date, I use them, otherwise
I call `compile` instead. Now it works. But I am not sure if this is quite right.

Instead of [the original code](https://github.com/intellifactory/websharper.warp/blob/a50a98f019745d14dd76af578b8a0e36b4bcd178/WebSharper.Warp/Warp.fs#L156-L158) I use

```fsharp
| _ ->
    if asm.IsDynamic then
        eprintfn "Assembly not compiled. When using Scripted = false, the application must be precompiled."
        None
    else
        let (+/) x y = Path.Combine(x, y)
        let dir = rootDir +/ "Scripts" +/ "WebSharper"
        let pathReadableJavaScript = dir +/ "WebSharper.EntryPoint.js"
        let pathCompressedJavaScript = dir +/ "WebSharper.EntryPoint.min.js"
        let toCompile =
            if not (File.Exists pathReadableJavaScript) || not (File.Exists pathCompressedJavaScript) then true
            else
                let asmTime = File.GetLastWriteTimeUtc asm.Location
                asmTime > (File.GetLastWriteTimeUtc pathReadableJavaScript) || asmTime > (File.GetLastWriteTimeUtc pathCompressedJavaScript)
        if toCompile then
            Debug.WriteLine "Compiling..."
            compile asm
        else
            Debug.WriteLine "Using compiled..."
            let opts = { FE.Options.Default with References = refs }
            let compiler = FE.Prepare opts (eprintfn "%O")
            Some {
                ReadableJavaScript = pathReadableJavaScript
                CompressedJavaScript = pathCompressedJavaScript
                Info = compiler.GetInfo()
                References = refs
            })
```

If the solution is fine I will make a PR. If something else is wrong (or I get this wrong) please let me know.

**Comment by granicz** [comment]
Hi @nightroman , sorry for the delay.  Warp needs a heavy revision and updating to the latest Zafir (WebSharper 4), and a lot of the shorthands it provides are already in the Zafir sitelets library. What's your scenario?  Are you doing interactive scripting with Warp?

**Comment by nightroman** [comment]
My scenario is somewhat "a friction-less scripted and standalone full-stack F#
client-server applications", as Warp describes itself. It is useful and easy to
use for prototyping in the first place. For prototyping, it is probably fine to
compile each time, even if the sources do not change.  But some prototypes may
stay is use. And some lightweight applications may be based on Warp.
It would be nice to avoid compilation if sources do not change.

This seems to be doable in some cases, and something was done in the past (#17).

Regardless of the scenario, it would be useful to know the purpose of the
option `scripted=false`.

If Warp needs a heavy revision then this is probably not a big deal now.
